### ISSUE TITLE
© mark at page footer should be colored white (?)

### ISSUE THREAD

**Issue by tsawada2** [harpseal-chan/JunkissaTrip#109]
ページフッダの©マークだけが、濃いグレーで表示されており、他のテキストが白字なので、違和感を覚えました。
<img width="180" alt="スクリーンショット 2022-10-18 0 20 12" src="https://user-images.githubusercontent.com/9572430/196218653-d1e7ef9d-4f37-40a8-9e47-e01a6ff39157.png">

©️ ←これは、絵文字（U+00A9 & U+FE0F）だからですね。

©　← 普通の文字（U+00A9） にすると、白字で統一できるかなと思いますが、いかがでしょうか？
<img width="160" alt="スクリーンショット 2022-10-18 0 29 36" src="https://user-images.githubusercontent.com/9572430/196219474-ac5a8d3f-0c19-488e-8075-f57e7d6ef073.png">

**Comment by harpseal-chan** [comment]
> ©　← 普通の文字（U+00A9） にすると、白字で統一できるかなと思いますが、いかがでしょうか？ <img alt="スクリーンショット 2022-10-18 0 29 36" width="160" src="https://user-images.githubusercontent.com/9572430/196219474-ac5a8d3f-0c19-488e-8075-f57e7d6ef073.png">

ご指摘ありがとうございます！修正します。
