### ISSUE TITLE
Standardize notation: 探す or さがす

### ISSUE THREAD

**Issue by tsawada2** [harpseal-chan/JunkissaTrip#123]
ヘッダーでは「（マップから）**探す**」となっていますが、他の箇所（例えば、トップページ）では「**さがす**」と表記されているところが多いように見えました。

表記をどちらかに統一するとより良いかなと思います。

**Comment by harpseal-chan** [comment]
ご指摘ありがとうございます！
表記を「探す」に統一しました。
