### ISSUE TITLE
Find from Map: Show all Junkissa locations from the beginning

### ISSUE THREAD

**Issue by tsawada2** [harpseal-chan/JunkissaTrip#125]
「マップから探す」機能を使っているとき、

1. どこか適当な場所にピンを立てて
2. 「周辺の純喫茶を探す」ボタンを押す

という2段階の操作が必要なので、ちょっと面倒に感じるときがありました。

提案ですが、マップ上に初めから登録されている純喫茶（を表すピン、今でいえば茶丸の「A」、「B」、「C」、…に当たるもの）を全て表示しておくのはどうでしょうか？

**Comment by harpseal-chan** [comment]
ありがとうございます！
ピンと周辺の純喫茶を探すボタンは削除して、マップ上にすべての店舗を表示するよう仕様を変更します。
店舗情報の表示方法も検討します。

**Comment by harpseal-chan** [comment]
> マップ上に初めから登録されている純喫茶（を表すピン、今でいえば茶丸の「A」、「B」、「C」、…に当たるもの）を全て表示しておくのはどうでしょうか？

下の画像のように、マップ上に純喫茶を示すピンをすべて表示しました。
ピン（茶色の丸）をクリックすると、上に店舗情報のウインドウが表示されます。
ウインドウ上の「詳細ページへ」をクリックすると店舗詳細ページへ遷移します。

<img width="1371" alt="スクリーンショット 2022-12-30 17 33 46" src="https://user-images.githubusercontent.com/102633054/210051047-6b68b62d-d696-43db-8263-28dcaa5d0377.png">

また、店舗の特徴による絞り込み機能をマップ検索ページにも搭載しました。

<img width="1158" alt="スクリーンショット 2022-12-30 17 34 56" src="https://user-images.githubusercontent.com/102633054/210051121-95659f8b-98a6-40f2-852f-dd0bb83f1615.png">

もし気になる点がありましたら、ご指摘をお願いいたします🙏
